### ISSUE TITLE
Quick question on comparison against BERT

### ISSUE THREAD

**Issue by hohoCode** [kimiyoung/transformer-xl#11]
Thanks for the codes! I am sure my question will be asked over and over and over again in near future. And I also read your paper which is all about comparison against vanilla transformer.

But still, in terms of performance, have you compared your great model against BERT? I mean it may not be a 100% fair comparison. But at the end of the day... which one (BERT or Tranformer-XL) is better on typical NLP tasks? Thanks.

**Comment by xwzhong** [comment]
agree, I also want to know

**Comment by kimiyoung** [comment]
- We don't know yet
- Transformer-XL has a lot of exciting potential applications, with pretraining being one of them. Based on the results we obtained in LM, Transformer-XL is better on both short and long sequences, which ideally should improve pretraining.
- We are working on it. Stay tuned for more update.

**Comment by hohoCode** [comment]
AWESOME. Look forward!!

**Comment by kimiyoung** [comment]
Architecture-wise, BERT is a plain Transformer. Al Rfou et al. have benchmarked Transformer's performance on language modeling.

**Comment by felixhao28** [comment]
True, but the main contribution of BERT is a way to pretrain a model that can be fine-tuned to different NLP tasks. It is not directly comparable to transformer-xl.
