### ISSUE TITLE
Different training steps in tf and pytorch

### ISSUE THREAD

**Issue by richardbaihe** [kimiyoung/transformer-xl#114]
Hi,
I notice that the training steps for the base_wt103 in PyTorch codes is 200K, while this number is 400K in the TF scripts. However, for the large wt103, both of them are 4M. 

I am confused about the training steps as I am training the large PyTorch model with 16*32GB v100. The speed is too slow to finish the 4000000 steps(1300ms per step,2 months, is it right? ).

By the way, will the tf codes be faster than PyTorch in this project?

Thanks for your help!

**Comment by menghuanlater** [comment]
I use pytorch1.5 to reproduce the sota result on wikitext-103 with single V100 GPU(32GB), I set the batch size to 12, after 2 hours of training about 3000 steps, I found the training ppl had down to 22.4, this probably means that you don't need a lot of GPUs and iteration steps?

**Comment by menghuanlater** [comment]
我的训练时间与这差不多，感觉太慢了，TF的速度与这差别并不大

**Comment by tonytan48** [comment]
@richardbaihe @menghuanlater Maybe 4 million is a typo. Did you try with training the transformer-xl model with 400K steps? In the paper, the authors mentioned they also just trained One billion word dataset for 400K steps, which is a much larger dataset.
@kimiyoung Hi, could you help to clarify on the training steps and maybe share some ideas on what is the GPU hours for training transformerXL large?

**Comment by richardbaihe** [comment]
Hi @tonytan48, I didn't train Transformer-xl large. But I trained my own [Segatron-XL large](https://arxiv.org/pdf/2004.14996.pdf). I got 18.3 ppl within 172k steps and 17.1 ppl within 352k steps. I guess Transformer-XL large model needs 400k to get 18.3 ppl instead of 4M.
