### ISSUE TITLE
TPU settings

### ISSUE THREAD

**Issue by stefan-it** [kimiyoung/transformer-xl#18]
Hi,

I would like to train a model on TPU, but I'm not able to find the correct settings for a *v2-8* TPU.

What parameters are needed for `NUM_HOST` and `NUM_CORE`? I tried different values, but I always get `num_replicas should be (8), got (XXX).` error messages.

What TPU model did you use for the 1 Billion word benchmark?

Can I create the `tfrecords` locally (on a non-TPU) in the `train_data` step?

Thanks :)

**Comment by kimiyoung** [comment]
Hey, if I understand correctly, you are using a v2 TPU with 8 cores. If that's the case, have you tried `NUM_HOST=1` and `NUM_CORE=8`?

**Comment by kimiyoung** [comment]
Yes you can create `tfrecords` locally, given that the `NUM_HOST` and `NUM_CORE` are consistent with your training specs.

**Comment by stefan-it** [comment]
Thanks @kimiyoung I'll try it and report it here later :)
