### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by loveJasmine** [kimiyoung/transformer-xl#19]
ub16c9@ub16c9-gpu:~/ub16_prj/transformer-xl/pytorch$ bash run_enwik8_base.sh train --work_dir enwiki8_task
Run training...
Experiment dir : enwiki8_task-enwik8/20190127-180347
Loading cached dataset...
====================================================================================================
    - clip : 0.25
    - eta_min : 0.0
    - finetune_v3 : False
    - n_layer : 12
    - pre_lnorm : False
    - n_head : 8
    - proj_init_std : 0.01
    - emb_init_range : 0.01
    - fp16 : False
    - n_nonemb_param : 40949760
    - scheduler : cosine
    - work_dir : enwiki8_task-enwik8/20190127-180347
    - batch_size : 22
    - debug : False
    - dropatt : 0.0
    - init_std : 0.02
    - lr : 0.00025
    - cuda : True
    - data : ../data/enwik8/
    - emb_init : normal
    - ext_len : 0
    - sample_softmax : -1
    - eval_tgt_len : 128
    - restart_dir : 
    - mom : 0.0
    - clamp_len : -1
    - max_eval_steps : -1
    - batch_chunk : 1
    - multi_gpu : True
    - mem_len : 512
    - dynamic_loss_scale : False
    - d_embed : 512
    - max_step : 400000
    - attn_type : 0
    - lr_min : 0.0
    - static_loss_scale : 1
    - init : normal
    - patience : 0
    - dropout : 0.1
    - finetune_v2 : False
    - d_head : 64
    - same_length : False
    - dataset : enwik8
    - init_range : 0.1
    - d_model : 512
    - tgt_len : 512
    - optim : adam
    - d_inner : 2048
    - warmup_step : 0
    - restart : False
    - seed : 1111
    - adaptive : False
    - n_token : 204
    - log_interval : 200
    - varlen : False
    - tied : True
    - clip_nonemb : False
    - decay_rate : 0.5
    - div_val : 1
    - gpu0_bsz : 4
    - not_tied : False
    - eval_interval : 4000
    - n_all_param : 41055436
====================================================================================================
#params = 41055436
#non emb params = 40949760
Traceback (most recent call last):
  File "train.py", line 539, in <module>
    train()
  File "train.py", line 445, in train
    ret = para_model(data, target, *mems)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ub16c9/ub16_prj/transformer-xl/pytorch/utils/data_parallel.py", line 64, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, device_ids)
  File "/home/ub16c9/ub16_prj/transformer-xl/pytorch/utils/data_parallel.py", line 80, in scatter
    bsz_unit = (bsz - gpu0_bsz) // (num_dev - 1)
ZeroDivisionError: integer division or modulo by zero
ub16c9@ub16c9-gpu:~/ub16_prj/transformer-xl/pytorch$

**Comment by kimiyoung** [comment]
If you only have one gpu, please remove `multi_gpu` and `gpu0_bsz` from your arguments.
