### ISSUE TITLE
Is transformer-xl like a seq2seq model or a word-embedding model?

### ISSUE THREAD

**Issue by huangnengCSU** [kimiyoung/transformer-xl#28]
Hi:
    I am reading the code of the model, but I can not find which part is encoder and which is decoder. So i want to know that is transformer-xl like a word-embedding layer as BERT instead of a seq2seq model? Thanks a lot.

**Comment by kimiyoung** [comment]
It's a language model, and could be used as an embedding model. When trained on large datasets, it could be a strong competitor of BERT.

**Comment by BinchaoPeng** [comment]
how can i use it  as an embedding model like using bert to extract feature,please?
