### ISSUE TITLE
Train a new corpus !

### ISSUE THREAD

**Issue by agemagician** [kimiyoung/transformer-xl#37]
What changes we need to perform inside the script to train in a new corpus ?

I have checked the script and there is a lot of if condition depend on each corpus.

**Comment by aletote** [comment]
I would also like to train on a new corpus on a character level please. Need instructions, thanks.

**Comment by zihangdai** [comment]
Step 1: Preprocess and encode your text into a file of "integer values" separated by space, where each integer represents a character / word. Then, split them into `train.txt, valid.txt, test.txt`. 
Step 2: Add a new `dataset` into the `Corpus` class in `data_utils.py` and define any additional preprocessing you want to perform (please refer to `enwik8` for character-level LM and `wt103` for word-level LM for concrete examples).
Step 3: Follow the bash script but change the dataset name and path to your own.

**Comment by aletote** [comment]
Thanks, so to encode characters into integer, can I just convert them into their ascii number?

**Comment by agemagician** [comment]
@zihangdai Do we have actually to convert words to integers ?
As I can see from Corpus class it calls "vocabulary" which build and encode the text.

**Comment by zihangdai** [comment]
Actually, you don't have to. In general, you only need space separated symbols, which can be words / chars / bytes.
