### ISSUE TITLE
PyTorch multiGPU training

### ISSUE THREAD

**Issue by AlexGrinch** [kimiyoung/transformer-xl#5]
Thank you for releasing such an awesome and easy to use code!

Could you, please, elaborate a little bit on PyTorch implementation multi GPU setup? More concretely, what does the parameter "gpu0_bsz" mean and what parameters should I change to scale this code to setups with the number of GPUs more (or less) than 4?

From the description it seems that "gpu0_bsz" is the batch size for GPU0, but it is not clear to me why it should differ from batch sizes on other GPUs.

**Comment by AlexGrinch** [comment]
I got it, thanks!

**Comment by guotong1988** [comment]
Thanks！
