### ISSUE TITLE
relative attention score

### ISSUE THREAD

**Issue by huining-zhn** [kimiyoung/transformer-xl#6]
hello,I have read this paper but I'm confused at the relative attention score. I don't know why the transpose(u) and the transpose(v) were defined separately as they seemed have the same meaning. Is there anything that I should consider ?

**Comment by kimiyoung** [comment]
u and v are two trainable parameters. We use separate parameters because they have different meanings -- u governs a global content bias and v encodes a global positional bias.

**Comment by huining-zhn** [comment]
I see. I always thought that they were deduced strictly from the absolute attention score, but now I understand what u and v mean. Thanks for your explanation.
