### ISSUE TITLE
Apparent logical error in GPU loss

### ISSUE THREAD

**Issue by jfelectron** [kimiyoung/transformer-xl#68]
In the cutoff index dependent conditional for updating loss, head_logprob appears to be used before it is ever defined. 

https://github.com/kimiyoung/transformer-xl/blob/44781ed21dbaec88b280f74d9ae2877f52b492a5/tf/model.py#L297

**Comment by kimiyoung** [comment]
it's defined at https://github.com/kimiyoung/transformer-xl/blob/44781ed21dbaec88b280f74d9ae2877f52b492a5/tf/model.py#L293
